export const PROFILE = Object.freeze({
    PRIVATE: 'PRIVATE',
    COMPANY: 'COMPANY'
})

export const NOTIFICATION_TYPES = Object.freeze({
    CONNECTION: 'CONNECTION',
    JOB_CREATED: 'JOB_CREATED',
    JOB_APPLICATION: 'JOB_APPLICATION',
    RECOMMENDATION: 'RECOMMENDATION',
    REVIEW: 'REVIEW'
})